export { default as home_left } from './images/home_left.png'
export { default as detail_left } from './images/detail_left.png'
export { default as bgsec1 } from './images/bgsec1.png'
export { default as bgsec2 } from './images/bgsec2.png'
export { default as prof_pic } from './images/madoc.png'
export { default as contact_bg } from './images/contact_bg.png'
export { default as contact_banner } from './images/contact_banner.png'
export { default as art_detail_accent } from './images/art_detail_accent.png'


// arts images

export { default as art1 } from './images/art1.png'
export { default as art2 } from './images/art2.png'
export { default as art3 } from './images/art3.png'


export { default as a1 } from './images/Artworks/4th-Dimension no.1.jpg'
export { default as a2 } from './images/Artworks/4th-Dimension no.4.jpg'
export { default as a3 } from './images/Artworks/4th-Dimension no.5.jpg'
export { default as a4 } from './images/artworks/Arabelle.jpg'
export { default as a5 } from './images/artworks/Bio-architecture no.4.jpg'
export { default as a6 } from './images/Artworks/Bio-architecture no.7.jpg'
export { default as a7 } from './images/artworks/Bio-architecture no.8.jpg'
export { default as a8 } from './images/artworks/Chromatic Cortex no.2.jpg'
export { default as a9 } from './images/artworks/Consciousness no.1.jpg'
export { default as a10 } from './images/artworks/Consciousness no.3.jpg'
export { default as a11 } from './images/artworks/Lungs.jpg'
export { default as a12 } from './images/artworks/Pathways no.1.jpg'
export { default as a13 } from './images/artworks/Pathways no.5.jpg'
export { default as a14 } from './images/artworks/Society no.1.jpg'
export { default as a15 } from './images/artworks/Society no.2.jpg'
export { default as a16 } from './images/artworks/Tongue.jpg'
export { default as a17 } from './images/artworks/Transcendence no.1.jpg'
export { default as a18 } from './images/artworks/Transcendence no.3.jpg'
export { default as a19 } from './images/artworks/Transcendence no.5.jpg'
export { default as a20 } from './images/artworks/Unity no.2.jpg'
export { default as a21 } from './images/artworks/XMachine no.1.jpg'
export { default as a22 } from './images/artworks/XMachine no.9.jpg'
export { default as a23 } from './images/artworks/AuditoriumShores.JPG'
export { default as a24 } from './images/artworks/Brain.JPG'
export { default as a25 } from './images/artworks/Eyes.JPG'
export { default as a26 } from './images/artworks/Heart.JPG'
export { default as a27 } from './images/artworks/Liquide.PNG'
export { default as a28 } from './images/artworks/Network.png'
export { default as a29 } from './images/artworks/Spine.jpg'
export { default as a30 } from './images/artworks/Train-Ride.jpg'
export { default as a31 } from './images/artworks/wolf.JPG'
export { default as a32 } from './images/artworks/Zentangle.JPG'
export { default as a33 } from './images/artworks/My Hand no.1.png'
export { default as a34 } from './images/artworks/My Hand no.2.png'