export { default as home_left } from './images/home_left.png'
export { default as bgsec1 } from './images/bgsec1.png'
export { default as bgsec2 } from './images/bgsec2.png'
export { default as prof_pic } from './images/madoc.png'
export { default as contact_bg } from './images/contact_bg.png'
export { default as contact_banner } from './images/contact_banner.png'


// arts images

export { default as art1 } from './images/art1.png'
export { default as art2 } from './images/art2.png'
export { default as art3 } from './images/art3.png'


export { default as a1 } from './images/a1.png'
export { default as a2 } from './images/a2.png'
export { default as a3 } from './images/a3.png'
export { default as a4 } from './images/a4.png'
export { default as a5 } from './images/a5.png'
export { default as a6 } from './images/a6.png'
export { default as a7 } from './images/a7.png'
export { default as a8 } from './images/a8.png'
export { default as a9 } from './images/a9.png'
export { default as a10 } from './images/a10.png'
export { default as a11 } from './images/a11.png'
export { default as a12 } from './images/a12.png'
export { default as a13 } from './images/a13.png'
export { default as a14 } from './images/a14.png'
export { default as a15 } from './images/a15.png'
export { default as a16 } from './images/a16.png'
export { default as a17 } from './images/a17.png'
export { default as a18 } from './images/a18.png'
export { default as a19 } from './images/a19.png'
export { default as a20 } from './images/a20.png'
export { default as a21 } from './images/a21.png'
export { default as a22 } from './images/a22.png'
export { default as a23 } from './images/a23.png'
export { default as a24 } from './images/a24.png'
export { default as a25 } from './images/a25.png'
export { default as a26 } from './images/a26.png'
export { default as a27 } from './images/a27.png'
export { default as a28 } from './images/a28.png'
export { default as a29 } from './images/a29.png'
export { default as a30 } from './images/a30.png'
