export { default as home_left } from './images/home_left.png'
export { default as detail_left } from './images/detail_left.png'
export { default as bgsec1 } from './images/bgsec1.png'
export { default as bgsec2 } from './images/bgsec2.png'
export { default as prof_pic } from './images/madoc.png'
export { default as contact_bg } from './images/contact_bg.png'
export { default as contact_banner } from './images/contact_banner.png'
export { default as art_detail_accent } from './images/art_detail_accent.png'


// arts images

export { default as art1 } from './images/art1.png'
export { default as art2 } from './images/art2.png'
export { default as art3 } from './images/art3.png'


export { default as a1 } from './images/Artworks/4th-Dimension1.png'
export { default as a2 } from './images/Artworks/4th-Dimension2.png'
export { default as a3 } from './images/Artworks/4th-Dimension3.png'
export { default as a4 } from './images/artworks/arabelle.png'
export { default as a5 } from './images/artworks/Bio-architecture1.png'
export { default as a6 } from './images/Artworks/Bio-architecture2.png'
export { default as a7 } from './images/artworks/Bio-architecture3.png'
export { default as a8 } from './images/artworks/ChromaticCortex.png'
export { default as a9 } from './images/artworks/1.png'
export { default as a10 } from './images/artworks/2.png'
export { default as a11 } from './images/artworks/3.png'
export { default as a12 } from './images/artworks/4.png'
export { default as a13 } from './images/artworks/5.png'
export { default as a14 } from './images/artworks/6.png'
export { default as a15 } from './images/artworks/7.png'
export { default as a16 } from './images/artworks/8.png'
export { default as a17 } from './images/artworks/9.png'
export { default as a18 } from './images/artworks/10.png'
export { default as a19 } from './images/artworks/11.png'
export { default as a20 } from './images/artworks/12.png'
export { default as a21 } from './images/artworks/13.png'
export { default as a22 } from './images/artworks/14.png'
export { default as a23 } from './images/artworks/15.png'
export { default as a24 } from './images/artworks/16.png'
export { default as a25 } from './images/artworks/17.png'
export { default as a26 } from './images/artworks/18.png'
export { default as a27 } from './images/artworks/19.png'
export { default as a28 } from './images/artworks/20.png'
export { default as a29 } from './images/artworks/21.png'
export { default as a30 } from './images/artworks/22.png'
export { default as a31 } from './images/artworks/23.png'
export { default as a32 } from './images/artworks/24.png'
export { default as a33 } from './images/artworks/25.png'
export { default as a34 } from './images/artworks/26.png'
export { default as a35 } from './images/artworks/27.png'
export { default as a36 } from './images/artworks/28.png'
export { default as a37 } from './images/artworks/29.png'
export { default as a38 } from './images/artworks/30.png'